spring:
  application:
    name: sensor-processing
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 9090

app:
  influxdb:
    url: http://localhost:8086
    token: GUREtJvgBg8s5IqwmqW3J2cEhYpjeQq_ghUDd4JtlF6n8NcOSSldA8OtsuLjl3n2n0Q95IiAVxo2P6E15oxsGg==
